on: [push]
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.14
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
    -name: Test
      run: |
        make test
    
